// <auto-generated />
using System;
using HabitTrackerProgram.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTrackerProgram.Migrations
{
    [DbContext(typeof(HabitContext))]
    [Migration("20251201133000_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HabitTrackerProgram.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabitTypeId");

                    b.ToTable("Habit");
                });

            modelBuilder.Entity("HabitTrackerProgram.Models.HabitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HabitType");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Running",
                            UnityName = "Km"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Eating",
                            UnityName = "KCal"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Reading",
                            UnityName = "Books"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Exercising",
                            UnityName = "Minutes"
                        });
                });

            modelBuilder.Entity("HabitTrackerProgram.Models.Habit", b =>
                {
                    b.HasOne("HabitTrackerProgram.Models.HabitType", "HabitType")
                        .WithMany()
                        .HasForeignKey("HabitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitType");
                });
#pragma warning restore 612, 618
        }
    }
}
